default_view:
  name: default_view
  view: true
  icon: mdi:home
  entities:
  - group.all_devices
  - group.all_automations
  - group.residents
  - group.all_lights
  - group.all_locks
  - group.all_remotes
  - group.all_scripts
  - group.all_switches
residents:
  name: Wie is er thuis?
  icon: mdi:account-multiple
  view: true
  entities:
  - device_tracker.nages_oneplus
  - device_tracker.ilses_htc
