home_latitude: 0.0
home_longitude: 0.0

nas_host: 0.0.0.0
nas_username: xxxxx
nas_password: xxxxx

axis_host: 0.0.0.0
axis_username: xxxxx
axis_password: xxxxx

xiaomi_aqara_host: 0.0.0.0
xiaomi_aqara_mac: AA:BB:CC:DD:EE:FF
xiaomi_aqara_key: xxxxx

telegram_api_key: 000000000:xxxxxxxxxxxxxxx
telegram_chat_id: 111111111

postgresql_uri: postgresql://xxxxx:xxxxx@0.0.0.0/xxxxx

mqtt_broker: 0.0.0.0
mqtt_username: xxxxx
mqtt_password: xxxxx
